version: '3.8'

services:
  python-app:
    build: .
    container_name: python_dev
    ports:
      - "8888:8888"
    volumes:
      - ./clustering:/app/clustering
      - ./data_collection_and_preprocessing:/app/data_collection_and_preprocessing
      - ./topic_identification:/app/topic_identification
      - ./sequential_analysis:/app/sequential_analysis
      - ./requirements.txt:/app/requirements.txt
    command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser
